<?php
/**
 * Admin Hooks.
 *
 * @package FormyChat
 * @since 1.0.0
 */

namespace FormyChat\Admin;

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

if ( ! class_exists( __NAMESPACE__ . '\\Hooks' ) ) {
	/**
	 * Admin hooks bootstrap.
	 */
	class Hooks extends \FormyChat\Base {

		/**
		 * Register hooks.
		 *
		 * @return void
		 */
		public function actions() {
			add_action( 'admin_init', [ $this, 'init_appsero' ], 0 );
			add_action( 'admin_init', [ $this, 'handle_safe_redirection' ] );
			add_action( 'admin_menu', [ $this, 'register_admin_menu' ], 10 );
			add_filter( 'plugin_action_links_' . plugin_basename( FORMYCHAT_FILE ), [ $this, 'plugin_action_links' ] );
		}

		/**
		 * Redirect to setup page on activation.
		 *
		 * @return void
		 */
		public function handle_safe_redirection() {
			if ( wp_doing_ajax() || wp_doing_cron() || ! current_user_can( 'manage_options' ) ) {
				return;
			}

			if ( wp_validate_boolean( get_option( 'scf-setup-run', false ) ) ) {
				return;
			}

			update_option( 'scf-setup-run', true, false );
			wp_safe_redirect( admin_url( 'admin.php?page=formychat' ) );
			exit;
		}

		/**
		 * Register admin menu pages.
		 *
		 * @return void
		 */
		public function register_admin_menu() {
			$capability = 'manage_options';

			add_menu_page(
				__( 'FormyChat', 'social-contact-form' ),
				__( 'FormyChat', 'social-contact-form' ),
				$capability,
				'formychat',
				[ $this, 'load_widget_app' ],
				'dashicons-formychat'
			);

			add_submenu_page(
				'formychat',
				__( 'Floating Widgets', 'social-contact-form' ),
				__( 'Floating Widgets', 'social-contact-form' ),
				$capability,
				'formychat',
				[ $this, 'load_widget_app' ]
			);

			add_submenu_page(
				'formychat',
				__( 'FormyChat Leads', 'social-contact-form' ),
				__( 'Leads', 'social-contact-form' ),
				$capability,
				'formychat-leads',
				[ $this, 'load_lead_app' ]
			);

			do_action( 'scf_admin_menu' );
		}

		/**
		 * Render widgets app mount with premium shell.
		 *
		 * @return void
		 */
		public function load_widget_app() {
			if ( ! current_user_can( 'manage_options' ) ) {
				wp_die( esc_html__( 'You are not allowed to access this page.', 'social-contact-form' ) );
			}

			echo '<div class="formychat-admin-shell" data-formychat-screen="widgets">';
			echo '<header class="formychat-admin-shell__header">';
			echo '<span class="formychat-admin-shell__badge">' . esc_html__( 'Control Center', 'social-contact-form' ) . '</span>';
			echo '<h1>' . esc_html__( 'Floating Widget Manager', 'social-contact-form' ) . '</h1>';
			echo '<p>' . esc_html__( 'Configure visual behavior, form channels and delivery preferences from a single workspace.', 'social-contact-form' ) . '</p>';
			echo '</header>';
			echo '<section class="formychat-admin-shell__content"><div id="formychat-widgets"></div></section>';
			echo '</div>';
		}

		/**
		 * Render leads app mount with premium shell.
		 *
		 * @return void
		 */
		public function load_lead_app() {
			if ( ! current_user_can( 'manage_options' ) ) {
				wp_die( esc_html__( 'You are not allowed to access this page.', 'social-contact-form' ) );
			}

			echo '<div class="formychat-admin-shell" data-formychat-screen="leads">';
			echo '<header class="formychat-admin-shell__header">';
			echo '<span class="formychat-admin-shell__badge">' . esc_html__( 'Lead Intelligence', 'social-contact-form' ) . '</span>';
			echo '<h1>' . esc_html__( 'Conversation Leads', 'social-contact-form' ) . '</h1>';
			echo '<p>' . esc_html__( 'Track submissions generated by widgets and connected form providers with a clean operational view.', 'social-contact-form' ) . '</p>';
			echo '</header>';
			echo '<section class="formychat-admin-shell__content"><div id="formychat-leads"></div></section>';
			echo '</div>';
		}

		/**
		 * Add plugin action links.
		 *
		 * @param array $links Plugin action links.
		 * @return array
		 */
		public function plugin_action_links( $links ) {
			if ( $this->is_ultimate_active() ) {
				$links[] = '<a href="' . esc_url( admin_url( 'admin.php?page=formychat' ) ) . '">' . esc_html__( 'Settings', 'social-contact-form' ) . '</a>';
			} else {
				$links[] = '<a href="https://go.wppool.dev/2rc7/?ref=' . rawurlencode( home_url() ) . '" target="_blank" rel="noopener noreferrer" style="color: #b32d2e;">' . esc_html__( 'Upgrade', 'social-contact-form' ) . '</a>';
			}

			return $links;
		}

		/**
		 * Initialize Appsero SDK.
		 *
		 * @return void
		 */
		public function init_appsero() {
			if ( ! class_exists( '\\Appsero\\Client' ) ) {
				require_once FORMYCHAT_INCLUDES . '/appsero/src/Client.php';
			}

			add_filter( 'appsero_is_local', '__return_false' );

			$appsero = new \Appsero\Client( '9b39bac1-3b27-41d1-aeec-18fbfd4a9977', 'FormyChat', FORMYCHAT_FILE );
			$appsero->insights()->init();

			if ( function_exists( 'wppool_plugin_init' ) ) {
				$bg_image = plugin_dir_url( FORMYCHAT_FILE ) . '/includes/wppool/background-image.png';
				wppool_plugin_init( 'social_contact_form', $bg_image );
			}
		}
	}

	Hooks::init();
}
