<?php
require __DIR__ . '/bootstrap.php';
require dirname( __DIR__ ) . '/jeito-performance-premium/includes/class-feature-flags.php';
require dirname( __DIR__ ) . '/jeito-performance-premium/includes/class-compatibility.php';
require dirname( __DIR__ ) . '/jeito-performance-premium/includes/class-integration-aiko.php';
require dirname( __DIR__ ) . '/jeito-performance-premium/includes/class-integration-bold-builder.php';
define( 'JPP_VERSION', '3.0.0' );
define( 'BT_BB_VERSION', '5.9.6' );
define( 'JPP_FILE', dirname( __DIR__ ) . '/jeito-performance-premium/jeito-performance-premium.php' );
require dirname( __DIR__ ) . '/jeito-performance-premium/includes/class-integration-cache.php';
require dirname( __DIR__ ) . '/jeito-performance-premium/includes/class-html-verifier.php';
require dirname( __DIR__ ) . '/jeito-performance-premium/includes/class-admin-dashboard.php';

$aiko = new JPP\Integration_Aiko();
ob_start();
$aiko->mobile_hero_css();
$css = ob_get_clean();
assert( false !== strpos( $css, '@media(max-width:767px)' ) );
assert( false !== strpos( $css, '.bt_bb_section.jpp-has-mobile-lcp .bt_bb_background_image_holder' ) );
assert( false === strpos( $css, 'contain-intrinsic-size:auto 800px' ) );
update_option( 'jpp_features', array( 'content_visibility' => true ) );
ob_start();
$aiko->mobile_hero_css();
$css = ob_get_clean();
assert( false !== strpos( $css, 'contain-intrinsic-size:auto 800px' ) );
assert( false !== strpos( $css, '.bt_bb_wrapper>.bt_bb_section.bt_bb_animation_no_animation:nth-child(n+3)' ) );
assert( false !== strpos( $css, '.bt_bb_css_post_grid' ) );
assert( false !== strpos( $css, '.ti-widget,.wpcf7' ) );
delete_option( 'jpp_features' );
$font_url = 'https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;1,700;1,900&display=swap';
$limited_font_url = $aiko->limit_front_page_font_axes( $font_url, 'boldthemes-fonts' );
assert( false !== strpos( $limited_font_url, 'Poppins:wght@300;400;500;700' ) );
$encoded_font_url = 'https://fonts.googleapis.com/css2?family=Poppins%3Aital%2Cwght%400%2C100%3B0%2C400%3B1%2C700';
assert( false !== strpos( $aiko->limit_front_page_font_axes( $encoded_font_url, 'bt_bb_google_fonts' ), 'Poppins:wght@300;400;500;700' ) );
assert( $font_url === $aiko->limit_front_page_font_axes( $font_url, 'other-fonts' ) );
assert( 'https://example.test/aiko/style.css' === $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' ) );
update_option( 'jpp_features', array( 'aiko_home_css' => true ) );
$modular_css_src = $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' );
assert( false !== strpos( $modular_css_src, 'assets/aiko-home.css' ) );
assert( false !== strpos( $modular_css_src, '?ver=3.0.0' ) );
$GLOBALS['jpp_post_content'] = '[products limit="4"]';
assert( 'https://example.test/aiko/style.css' === $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' ) );
$GLOBALS['jpp_post_content'] = '<!-- wp:woocommerce/product-collection /-->';
assert( 'https://example.test/aiko/style.css' === $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' ) );
$GLOBALS['jpp_post_content'] = '';
$GLOBALS['jpp_sidebars_widgets'] = array( 'header' => array( 'woocommerce_widget_cart-2' ) );
assert( 'https://example.test/aiko/style.css' === $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' ) );
$GLOBALS['jpp_sidebars_widgets'] = array( 'wp_inactive_widgets' => array( 'woocommerce_widget_cart-2' ), 'orphaned_widgets_1' => array( 'woocommerce_products-3' ) );
assert( false !== strpos( $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' ), 'assets/aiko-home.css' ) );
$GLOBALS['jpp_sidebars_widgets'] = array();
$GLOBALS['jpp_is_woocommerce'] = true;
assert( 'https://example.test/aiko/style.css' === $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' ) );
$GLOBALS['jpp_is_woocommerce'] = false;
$GLOBALS['jpp_theme_stylesheet'] = 'aiko-child';
assert( 'https://example.test/aiko/style.css' === $aiko->home_stylesheet_src( 'https://example.test/aiko/style.css', 'aiko-style' ) );
$GLOBALS['jpp_theme_stylesheet'] = 'aiko';
delete_option( 'jpp_features' );
assert( true === JPP\Compatibility::aiko() );
$GLOBALS['jpp_theme_version'] = '1.1.0';
assert( false === JPP\Compatibility::aiko() );
assert( $font_url === $aiko->limit_front_page_font_axes( $font_url, 'boldthemes-fonts' ) );
$GLOBALS['jpp_theme_version'] = '1.0.5';
assert( true === JPP\Compatibility::bold_builder() );
$verifier = new JPP\Admin_Dashboard();
$served = '<div class="bt_bb_parallax"></div><style>contain-intrinsic-size:auto 800px</style><picture><source media="(max-width:767px)" srcset="https://example.test/hero.webp"><img class="jpp-mobile-lcp" src="data:image/gif;base64,AA" loading="eager" fetchpriority="high"></picture><div class="bt_bb_css_post_grid"></div><script>window.jppDeferredGridEnqueued=true</script><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700">';
$verification = $verifier->inspect_html( $served );
assert( true === $verification['passed'] );
assert( strlen( $served ) === $verification['bytes'] );
$failed_verification = $verifier->inspect_html( '<div class="bt_bb_parallax bt_bb_css_post_grid"></div><link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;1,900">' );
assert( false === $failed_verification['passed'] );
$no_priority = str_replace( 'fetchpriority="high"', 'fetchpriority="auto"', $served );
assert( false === $verifier->inspect_html( $no_priority )['checks']['lcp_priority'] );
$css_marker_only = '<link rel="preload" as="image" href="https://example.test/hero.webp" fetchpriority="high"><div class="bt_bb_parallax"></div><style>.jpp-mobile-lcp{display:none}</style>';
assert( false === $verifier->inspect_html( $css_marker_only )['checks']['hero'] );
$mixed_fonts = $served . '<link href="https://fonts.googleapis.com/css2?family=Play:ital,wght@0,400;1,900">';
assert( false === $verifier->inspect_html( $mixed_fonts )['checks']['font_axes'] );
$encoded_fonts = str_replace( 'Poppins:wght@300;400;500;700', 'Poppins%3Awght%40300%3B400%3B500%3B700', $served );
assert( true === $verifier->inspect_html( $encoded_fonts )['checks']['font_axes'] );
$not_applicable = $verifier->inspect_html( '<style>contain-intrinsic-size:auto 800px</style>' );
assert( true === $not_applicable['checks']['hero'] );
assert( true === $not_applicable['checks']['deferred_grid'] );
assert( true === $not_applicable['checks']['font_axes'] );
update_option( 'jpp_features', array( 'aiko_home_css' => true ) );
assert( false === $verifier->inspect_html( $served )['checks']['aiko_home_css'] );
assert( true === $verifier->inspect_html( $served . '<link rel="stylesheet" href="/wp-content/plugins/jeito-performance-premium/assets/aiko-home.css">' )['checks']['aiko_home_css'] );
delete_option( 'jpp_features' );

$builder = new JPP\Integration_Bold_Builder();
$section = '<section class="bt_bb_section"><div class="bt_bb_background_image_holder bt_bb_parallax" style="background-image: url(&quot;https://cdn.example.test/hero.webp&quot;)"></div></section>';
$hero = $builder->render_mobile_lcp_image( $section, 'bt_bb_section', array(), array() );
assert( false !== strpos( $hero, 'jpp-has-mobile-lcp' ) );
assert( false !== strpos( $hero, 'srcset="https://cdn.example.test/hero.webp"' ) );
assert( false !== strpos( $hero, 'fetchpriority="high"' ) );
assert( $section === $builder->render_mobile_lcp_image( $section, 'bt_bb_section', array(), array() ) );
$plain_builder = new JPP\Integration_Bold_Builder();
assert( '<section class="bt_bb_section"></section>' === $plain_builder->render_mobile_lcp_image( '<section class="bt_bb_section"></section>', 'bt_bb_section', array(), array() ) );
$builder->enqueue_deferred_grid();
assert( empty( $GLOBALS['jpp_scripts']['jpp-deferred-post-grid'] ) );
$GLOBALS['jpp_scripts']['bt_bb_css_post_grid'] = true;
$builder->enqueue_deferred_grid();
assert( array( 'bt_bb_css_post_grid' ) === $GLOBALS['jpp_scripts']['jpp-deferred-post-grid']['deps'] );
assert( 'window.jppDeferredGridEnqueued=true;' === $GLOBALS['jpp_inline_scripts']['jpp-deferred-post-grid']['before'] );
$sanitized = JPP\Feature_Flags::sanitize( array( 'mobile_hero' => '1', 'unknown' => '1' ) );
assert( true === $sanitized['mobile_hero'] );
assert( false === $sanitized['content_visibility'] );
assert( false === $sanitized['deferred_grid'] );
assert( false === $sanitized['font_axes'] );
update_option( 'jpp_features', array( 'mobile_hero' => false, 'content_visibility' => false, 'deferred_grid' => false, 'font_axes' => false ) );
assert( false === JPP\Feature_Flags::enabled( 'mobile_hero' ) );
assert( $font_url === $aiko->limit_front_page_font_axes( $font_url, 'boldthemes-fonts' ) );
$disabled_builder = new JPP\Integration_Bold_Builder();
assert( $section === $disabled_builder->render_mobile_lcp_image( $section, 'bt_bb_section', array(), array() ) );

$admin_css = file_get_contents( dirname( __DIR__ ) . '/jeito-performance-premium/assets/admin.css' );
assert( false !== strpos( $admin_css, 'backdrop-filter:blur(24px)' ) );
assert( false !== strpos( $admin_css, '@media(prefers-reduced-motion:reduce)' ) );
$admin_js = file_get_contents( dirname( __DIR__ ) . '/jeito-performance-premium/assets/admin.js' );
assert( false !== strpos( $admin_js, "event.key === 'Escape'" ) );
assert( false !== strpos( $admin_js, "event.key !== 'Tab'" ) );
$grid_js = file_get_contents( dirname( __DIR__ ) . '/jeito-performance-premium/assets/deferred-post-grid.js' );
assert( false !== strpos( $grid_js, 'IntersectionObserver' ) );
assert( false !== strpos( $grid_js, "rootMargin: '200px 0px'" ) );

$cache = new JPP\Integration_Cache();
$GLOBALS['jpp_test_options']['jpp_installed_version'] = '2.2.0';
$GLOBALS['jpp_test_options']['jpp_features'] = array( 'mobile_hero' => true, 'content_visibility' => true, 'deferred_grid' => true, 'font_axes' => true, 'aiko_home_css' => false );
$cache->register();
assert( false === get_option( 'jpp_features' )['content_visibility'] );
assert( true === get_option( 'jpp_features' )['mobile_hero'] );
assert( '3.0.0' === get_option( 'jpp_cache_flush_pending' ) );
assert( true === $cache->maybe_flush() );
assert( 1 === $GLOBALS['jpp_cache_flush_count'] );
assert( '' === get_option( 'jpp_cache_flush_pending', '' ) );
assert( 'wordpress' === get_option( 'jpp_last_cache_flush' )['provider'] );
assert( false === $cache->maybe_flush() );
assert( 1 === $GLOBALS['jpp_cache_flush_count'] );
$cache->schedule_after_feature_change( array( 'mobile_hero' => true ), array( 'mobile_hero' => false ) );
assert( '3.0.0' === get_option( 'jpp_cache_flush_pending' ) );
assert( true === $cache->maybe_flush() );
assert( 2 === $GLOBALS['jpp_cache_flush_count'] );
$cache->schedule_after_feature_change( array( 'mobile_hero' => false ), array( 'mobile_hero' => false ) );
assert( '' === get_option( 'jpp_cache_flush_pending', '' ) );
$cache->schedule_after_feature_add( 'unrelated_option', array( 'mobile_hero' => false ) );
assert( '' === get_option( 'jpp_cache_flush_pending', '' ) );
$cache->schedule_after_feature_add( 'jpp_features', array( 'mobile_hero' => false ) );
assert( '3.0.0' === get_option( 'jpp_cache_flush_pending' ) );
assert( true === $cache->maybe_flush() );
assert( 3 === $GLOBALS['jpp_cache_flush_count'] );
$GLOBALS['jpp_cache_flush_result'] = false;
$cache->schedule_after_feature_change( array( 'font_axes' => true ), array( 'font_axes' => false ) );
assert( false === $cache->maybe_flush() );
assert( '3.0.0' === get_option( 'jpp_cache_flush_pending' ) );
assert( 1 === get_option( 'jpp_cache_flush_attempts' ) );
assert( false === $cache->maybe_flush() );
assert( '3.0.0' === get_option( 'jpp_cache_flush_pending' ) );
assert( false === $cache->maybe_flush() );
assert( '' === get_option( 'jpp_cache_flush_pending', '' ) );
assert( '' === get_option( 'jpp_cache_flush_attempts', '' ) );
assert( 3 === get_option( 'jpp_last_cache_flush' )['attempts'] );

echo "All integration tests passed.\n";
